# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(820, 556)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(235, 255, 225);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_OpenWebcam = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_OpenWebcam.setGeometry(QtCore.QRect(30, 170, 151, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_OpenWebcam.setFont(font)
        self.btn_OpenWebcam.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_OpenWebcam.setObjectName("btn_OpenWebcam")
        self.lbl_Webcam = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_Webcam.setGeometry(QtCore.QRect(200, 40, 611, 481))
        self.lbl_Webcam.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lbl_Webcam.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.lbl_Webcam.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.lbl_Webcam.setLineWidth(3)
        self.lbl_Webcam.setText("")
        self.lbl_Webcam.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_Webcam.setObjectName("lbl_Webcam")
        self.btn_CloseWebcam = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_CloseWebcam.setGeometry(QtCore.QRect(30, 280, 151, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_CloseWebcam.setFont(font)
        self.btn_CloseWebcam.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_CloseWebcam.setObjectName("btn_CloseWebcam")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(350, 10, 341, 31))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 820, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Real time face mask detection"))
        self.btn_OpenWebcam.setText(_translate("MainWindow", "Open webcam"))
        self.btn_CloseWebcam.setText(_translate("MainWindow", "Close webcam"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#ff0000;\">Real time face mask detection</span></p></body></html>"))
